/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_proto_5fmulticast_2eproto__INCLUDED
#define PROTOBUF_C_proto_5fmulticast_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _MulticastMsg MulticastMsg;


/* --- enums --- */


/* --- messages --- */

struct  _MulticastMsg
{
  ProtobufCMessage base;
  size_t n_c;
  uint64_t *c;
};
#define MULTICAST_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&multicast_msg__descriptor) \
    , 0,NULL }


/* MulticastMsg methods */
void   multicast_msg__init
                     (MulticastMsg         *message);
size_t multicast_msg__get_packed_size
                     (const MulticastMsg   *message);
size_t multicast_msg__pack
                     (const MulticastMsg   *message,
                      uint8_t             *out);
size_t multicast_msg__pack_to_buffer
                     (const MulticastMsg   *message,
                      ProtobufCBuffer     *buffer);
MulticastMsg *
       multicast_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   multicast_msg__free_unpacked
                     (MulticastMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MulticastMsg_Closure)
                 (const MulticastMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor multicast_msg__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_proto_5fmulticast_2eproto__INCLUDED */
